### ISSUE TITLE
Setup route on backend

### ISSUE THREAD

**Issue by NatalieBurks** [gannonprudhomme/CSCE-482-KNOW-backend#5]
We need to set up some route on the frontend that will take some URI and return the parse RDF for it, e.g.

```
GET /get_rdf_data?uri=wikidata.org/wiki/Q2399837
```

would return

```json
{
  "type": "person",
  "name": "First Last",
  "birthDate": "2021-01-01T00:00:00+6",
  "title": ["Poet", "Artist"],
}
```

**Comment by gannonprudhomme** [comment]
Since the web framework is setup, I changed this to "Setup route on backend" and added a description

**Comment by gannonprudhomme** [comment]
An idea I had: instead of sending what type of entity the person is and each of their fields, we can instead send data like:
```json
{
  "title": "person name",
  "subtitle": "Poet",
  "description": "A bunch of words here if we can find them",
  "entries": {
    "birthDate": { "text": "Birth day", "value": "August 23rd, 1964" },
    "deathDate": null,
  },
}
```
or for a book it would look like
```json
{
  "title": "Dune",
  "subtitle": "Novel by Frank Herbert",
  "description": "A bunch of words here if we can find them",
  "entries": {
    "publishDate": { "text": "Published", "value": "August 23rd, 1964" },
    "author": "Frank Herbert"
  },
}
```

Basically, this way we leave the determining of what goes where in the knowledge panel on the backend rather than on the frontend. It'll just make the frontend's job easier, since we won't have to format the data into how we would like it.
